#!/usr/bin/env bash
# Generate local broker credentials for `docker compose up`.
#
# Writes (both git-ignored):
#   .env                     AURA_MQTT_USERNAME / AURA_MQTT_PASSWORD / AURA_REDIS_PASSWORD / AURA_REDIS_URL
#   deploy/mosquitto/passwd  mosquitto_passwd hash file mounted into the broker
#
# Re-running rotates nothing unless --force is passed.
set -euo pipefail

repo_root="$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)"
env_file="$repo_root/.env"
passwd_file="$repo_root/deploy/mosquitto/passwd"
force="${1:-}"

if [[ -f "$env_file" && "$force" != "--force" ]]; then
  echo "$env_file already exists (pass --force to regenerate)"
  exit 0
fi

mqtt_user="aura"
mqtt_pass="$(openssl rand -base64 24 | tr -d '/+=' | cut -c1-24)"
redis_pass="$(openssl rand -base64 24 | tr -d '/+=' | cut -c1-24)"

umask 077
cat > "$env_file" <<EOF
# Generated by deploy/init_secrets.sh -- never commit this file.
AURA_MQTT_HOST=127.0.0.1
AURA_MQTT_PORT=1883
AURA_MQTT_USERNAME=$mqtt_user
AURA_MQTT_PASSWORD=$mqtt_pass
AURA_REDIS_PASSWORD=$redis_pass
AURA_REDIS_URL=redis://:$redis_pass@127.0.0.1:6379
AURA_DASHBOARD_PASSWORD=$(openssl rand -base64 18 | tr -d '/+=' | cut -c1-18)
EOF

mkdir -p "$(dirname "$passwd_file")"
: > "$passwd_file"
docker run --rm -i -v "$(dirname "$passwd_file")":/work eclipse-mosquitto:2 \
  mosquitto_passwd -b /work/passwd "$mqtt_user" "$mqtt_pass"
chmod 600 "$passwd_file"

echo "wrote $env_file and $passwd_file"
echo "load them with: set -a && source .env && set +a"
